In [472]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/titanic/gender_submission.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/train.csv


In [473]:
raw_train_data=pd.read_csv("../input/titanic/train.csv")
raw_test_data=pd.read_csv("../input/titanic/test.csv")

In [474]:
raw_train_data['Age']=raw_train_data['Age'].fillna(value=np.mean(raw_train_data['Age']))
raw_test_data['Age']=raw_test_data['Age'].fillna(value=np.mean(raw_test_data['Age']))

raw_train_data['Fare']=raw_train_data['Fare'].fillna(value=np.mean(raw_train_data['Fare']))
raw_test_data['Fare']=raw_test_data['Fare'].fillna(value=np.mean(raw_test_data['Fare']))

In [475]:
raw_train_data['Cabin']=raw_train_data['Cabin'].fillna(0)
raw_test_data['Cabin']=raw_test_data['Cabin'].fillna(0)


raw_train_data['Cabin']=raw_train_data['Cabin'].replace(to_replace=0,value='XXX')
raw_test_data['Cabin']=raw_test_data['Cabin'].replace(to_replace=0,value='XXX')

In [476]:
raw_train_data['Sex']=raw_train_data['Sex'].replace(to_replace='female',value='1',regex=True)
raw_train_data['Sex']=raw_train_data['Sex'].replace(to_replace='male',value='0',regex=True)
raw_test_data['Sex']=raw_test_data['Sex'].replace(to_replace='female',value='1',regex=True)
raw_test_data['Sex']=raw_test_data['Sex'].replace(to_replace='male',value='0',regex=True)

In [477]:
train_cabin=raw_train_data['Cabin'].unique()
test_cabin=raw_test_data['Cabin'].unique()
cabin_combined=np.append(train_cabin,test_cabin)

In [478]:
cabin=np.unique(cabin_combined)

In [479]:
cabin.size

187

In [480]:
cabin_val=np.arange(187)

In [481]:
test_data=raw_test_data
train_data=raw_train_data

In [482]:
train_data=train_data.replace(to_replace=cabin,value=cabin_val)
test_data=test_data.replace(to_replace=cabin,value=cabin_val)

In [483]:
train_data['Embarked']=train_data['Embarked'].fillna(value='X')
emb=train_data['Embarked'].unique()
emb_val=np.arange(4)
train_data=train_data.replace(to_replace=emb,value=emb_val)
test_data=test_data.replace(to_replace=emb,value=emb_val)

In [484]:
train_data=train_data.sort_values(by=['PassengerId'])
test_data=test_data.sort_values(by=['PassengerId'])

In [485]:
X_train=train_data[['Pclass','Sex','Age','SibSp','Parch','Cabin','Fare','Embarked']]
X_test=test_data[['Pclass','Sex','Age','SibSp','Parch','Cabin','Fare','Embarked']]
y_train=train_data['Survived']

In [486]:
from sklearn.preprocessing import StandardScaler
s1=StandardScaler()
s2=StandardScaler()
X_train=s1.fit(X_train).transform(X_train)
X_test=s2.fit(X_test).transform(X_test)

In [487]:
test_data.head(12)

PassengerId  Pclass                                          Name Sex  \
0           892       3                              Kelly, Mr. James   0   
1           893       3              Wilkes, Mrs. James (Ellen Needs)   1   
2           894       2                     Myles, Mr. Thomas Francis   0   
3           895       3                              Wirz, Mr. Albert   0   
4           896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   1   
5           897       3                    Svensson, Mr. Johan Cervin   0   
6           898       3                          Connolly, Miss. Kate   1   
7           899       2                  Caldwell, Mr. Albert Francis   0   
8           900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)   1   
9           901       3                       Davies, Mr. John Samuel   0   
10          902       3                              Ilieff, Mr. Ylio   0   
11          903       1                    Jones, Mr. Charles Cresson   0   

         Age  SibSp  Parch     Ticket     Fare  Cabin Embarked  
0   34.50000      0      0     330911   7.8292    186        2  
1   47.00000      1      0     363272   7.0000    186        0  
2   62.00000      0      0     240276   9.6875    186        2  
3   27.00000      0      0     315154   8.6625    186        0  
4   22.00000      1      1    3101298  12.2875    186        0  
5   14.00000      0      0       7538   9.2250    186        0  
6   30.00000      0      0     330972   7.6292    186        2  
7   26.00000      1      1     248738  29.0000    186        0  
8   18.00000      0      0       2657   7.2292    186        1  
9   21.00000      2      0  A/4 48871  24.1500    186        0  
10  30.27259      0      0     349220   7.8958    186        0  
11  46.00000      0      0        694  26.0000    186        0

In [488]:
raw_test_data.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  418.000000  418.000000  418.000000  418.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   12.634534    0.896760    0.981429   55.840500
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   23.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   30.272590    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   35.750000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [489]:
test_check=test_data.isnull()
test_check['Fare'].unique()

array([False])

In [490]:
test_data['Fare'].unique()

array([  7.8292    ,   7.        ,   9.6875    ,   8.6625    ,
        12.2875    ,   9.225     ,   7.6292    ,  29.        ,
         7.2292    ,  24.15      ,   7.8958    ,  26.        ,
        82.2667    ,  61.175     ,  27.7208    ,  12.35      ,
         7.225     ,   7.925     ,  59.4       ,   3.1708    ,
        31.6833    ,  61.3792    , 262.375     ,  14.5       ,
        61.9792    ,  30.5       ,  21.6792    ,  31.5       ,
        20.575     ,  23.45      ,  57.75      ,   8.05      ,
         9.5       ,  56.4958    ,  13.4167    ,  26.55      ,
         7.85      ,  13.        ,  52.5542    ,  29.7       ,
         7.75      ,  76.2917    ,  15.9       ,  60.        ,
        15.0333    ,  23.        , 263.        ,  15.5792    ,
        29.125     ,   7.65      ,  16.1       ,  13.5       ,
         7.725     ,  21.        ,   7.8792    ,  42.4       ,
        28.5375    , 211.5       ,  25.7       ,  15.2458    ,
       221.7792    ,  10.7083    ,  14.4542    ,  13.9 

In [491]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(C=0.001,solver='liblinear').fit(X_train,y_train)
y_pred=model.predict(X_test)

In [492]:
y_pred

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [504]:
test_out=pd.DataFrame(test_data['PassengerId'],columns=["PassengerId"])
test_out['Survived']=y_pred
#test_out=pd.DataFrame(y_pred,columns=["Survived"])

In [505]:
test_out

Survived
0           0
1           0
2           0
3           0
4           1
..        ...
413         0
414         1
415         0
416         0
417         0

[418 rows x 1 columns]